---
- hosts: localhost
  connection: local
  tasks:
   - name: Create a VM
     delegate_to: localhost
     vsphere_guest:
      vcenter_hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_passwd }}"
      esxi:
        datacenter: ha-datacenter
        hostname: "{{ vcenter_hostname }}"
      validate_certs: no
      guest: "{{ vm_name }}"
      state: powered_on
      vm_extra_config:
        vcpu.hotadd: yes
        mem.hotadd:  yes
        notes: This is a test VM
      vm_disk:
        disk1:
          size_gb: 10
          type: thin
          datastore: "{{ datastore }}"
      vm_nic:
        nic1:
          type: vmxnet3
          network: "{{ network }}"
          network_type: standard
      vm_hardware:
        memory_mb: 1536
        num_cpus: 1
        osid: centos7_64Guest
        scsi: paravirtual

   - name: Collect Facts
     delegate_to: localhost
     vsphere_guest:
      vcenter_hostname: "{{ vcenter_hostname }}"
      validate_certs: no
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_passwd }}"
      guest: "{{ vm_name }}"
      vmware_guest_facts: yes
     register: vmfacts

   - name: Print MAC mac_address
     debug:
      msg: "{{ vmfacts.ansible_facts }} {{ vm_name }}"
      #msg: "{{ vmfacts.ansible_facts.hw_eth0.macaddress }} {{ vm_name }}"

   - name: Restart VM
     delegate_to: localhost
     vsphere_guest:
       vcenter_hostname: "{{ vcenter_hostname }}"
       validate_certs: no
       username: "{{ vcenter_user }}"
       password: "{{ vcenter_passwd }}"
       guest: "{{ vm_name }}"
       state: restarted
